import Head from "next/head";
import "tailwindcss/tailwind.css";

export default function Home() {
  return (
    <div className="m-0 p-0">
      <Head>
        <title>Create padlet clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-orange-500 py-2">
        <p className=" ml-2 text-xs text-orange-400">Company</p>
        <div className="ml-20">
          <h1 className="text-2xl mt-7 font-bold text-white">Title this is the title</h1>
          <h2 className="text-slate-100">Descriptio</h2>
        </div>
      </section>
      <section className="bg-orange-400 pb-10"> 
          
      </section>
    </div>
  );
}

//  참... 이거 JIT 안되어있ㄴㅇ 흐규휴ㅠㅎ규휴규규규
