import React, { useState } from "react";
import Head from "next/head";
import "tailwindcss/tailwind.css";
import Card from "../components/card";

export default function Home() {
  const [Cards, setCards] = useState([]);
  const [CmakebarState, setCmakebarState] = useState(false);
  const [CbarInputValue, setCbarInputValue] = useState({title: '', content: ''});

  function cardmakebar() {
    if (CmakebarState === true) {
      setCmakebarState(false);
    } else if (CmakebarState === false) {
      setCmakebarState(true);
    }
  }
  
  function handleNewCard() {
    if (CbarInputValue === '') return;

    setCards([...Cards, CbarInputValue]);
  }

  return (
    <div className="m-0 p-0 w-full h-full">
      <Head>
        <title>Create padlet clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="rounded-lg fixed z-10 w-full top-0 bg-orange-500 py-3 shadow-sms">
        <p className=" ml-2 text-xs text-orange-400">Company</p>
        <div className="ml-20">
          <h1 className="text-2xl mt-7 font-bold text-white">
            Title this is the title
          </h1>
          <h2 className="text-slate-100">Descriptio</h2>
        </div>
      </section>
      
      <section className="inline-block mt-32  z-10 mb-4 w-full">
        {Cards.map((card, i) => (
          <Card key={i} title={card.title} content={card.content} />
        ))}
      </section>
      <button onClick={cardmakebar}>press!</button>
      {
        CmakebarState &&(<div className="fixed top-50 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-white m-20 z-0">
          <input placeholder="title for a new card" onChange={e => {setCbarInputValue({title: e.target.value, content: CbarInputValue.content})}}></input>
          <input placeholder="content for a new card" onChange={e => {setCbarInputValue({title: CbarInputValue.title, content: e.target.value})}}></input>
          <button onClick={handleNewCard}>save</button>
        </div>)
      }
    </div>
  );
}
